#
# Copyright (C) 2015-2016 Cryogenic Graphics Ltd
#

Import('env')

localEnv = env.Clone()

localEnv.AppendUnique(LIBS = ['riot', 'boost_program_options'])
localEnv.Append(LINKFLAGS = '-Wno-maybe-uninitialized')

localEnv.AddUnitTest('nmea_reader', 'nmea_reader.cpp')

if not GetOption('clang') :
  localEnv.Program('gpscontrol', 'gpscontrol.cpp')
