#
# Copyright (C) 2015-2016 Cryogenic Graphics Ltd
#

Import('env')

env.StaticLibrary('riot', Glob('*.cpp'))

env.AppendUnique(CPPPATH = '#/' + env['VariantDir'] + '/include')
env.AppendUnique(LIBPATH = '#/' + env['VariantDir'])
